---
- hosts: all
  become: yes
  vars_files:
  - vars/{{ stage }}.yml
  pre_tasks:
  - name: "Install etckeeper"
    apt: name=etckeeper
  roles:
  - role: znz.ufw
    ufw_default_forward_policy: reject
    ufw_allow_in_tcp:
    - comment: "HTTP"
      port: 80
    - comment: "HTTPS"
      port: 443
    - comment: "SSH"
      port: 22
    ufw_limit_in_tcp: []
    ufw_allow_out_tcp:
    - comment: "HTTP"
      port: 80
    - comment: "SSH"
      port: 22
    - comment: "SMTPS"
      port: 465
  - role: znz.journald
  - role: znz.sshd
  - role: znz.unattended-upgrades
  - role: znz.nadoka
  - role: mailuser
  - role: znz.dovecot-postfix
  - role: znz.dehydrated
  - role: apache2
  - role: znz.chkbuild
    chkbuild_timer: "OnCalendar=*-*-* 00:00:00"
    chkbuild_resource_control: |
      CPUQuota=50%
  - role: apache2
    apache2_server_name: "{{ chkbuild_domain }}"
    apache2_server_alias: ~
    apache2_document_root: "/home/chkbuild/public_html/"
    apache2_site_conf: "{{ chkbuild_site_conf }}"
    apache2_site_ssl_conf: "{{ chkbuild_site_conf }}"
    apache2_ssl_certificate_file: "/var/lib/dehydrated/certs/{{ chkbuild_domain }}/fullchain.pem"
    apache2_ssl_certificate_key_file: "/var/lib/dehydrated/certs/{{ chkbuild_domain }}/privkey.pem"

  tasks:
  - name: 'Comment out 127.0.1.1 in /etc/hosts'
    replace:
      path: /etc/hosts
      regexp: '^(127\.0\.1\.1)'
      replace: '#\1'
  - name: 'Install logwatch'
    apt: name=logwatch
  - name: "Install chkbuild dependencies"
    apt:
      name: "{{ item }}"
    with_items:
    - subversion
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - zlib1g-dev
